"""Creacion de tablas accesorio y telefono_accesorio

Revision ID: 1adc83351dba
Revises: 315a488c45ff
Create Date: 2024-08-06 20:31:01.888936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adc83351dba'
down_revision = '315a488c45ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefono__accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono_id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorio.id'], ),
    sa.ForeignKeyConstraint(['telefono_id'], ['telefono.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefono__accesorio')
    op.drop_table('accesorio')
    # ### end Alembic commands ###
