"""Modificaciones 10/8

Revision ID: 29619432cd5e
Revises: 1adc83351dba
Create Date: 2024-08-10 11:13:21.861286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29619432cd5e'
down_revision = '1adc83351dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['telefono_id'], ['telefono.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    # ### end Alembic commands ###
