"""modificacion en venta

Revision ID: bad55a3cb4c8
Revises: a7116deb837c
Create Date: 2024-10-17 11:36:07.465106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bad55a3cb4c8'
down_revision = 'a7116deb837c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint('venta_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('venta_ibfk_1', 'cliente', ['cliente_id'], ['id'])
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
